import os
import re
import json
from collections import defaultdict, Counter
from collections import OrderedDict

root = "/data1/VQA_ready_data"
groups = defaultdict(list)
final_stats = {}

for name in os.listdir(root):
    fpath = os.path.join(root, name)
    if not os.path.isdir(fpath):
        continue
    if "_" in name and name.split("_")[-1].isdigit():
        prefix = "_".join(name.split("_")[:-1])
    else:
        prefix = name
    groups[prefix].append(fpath)

def contains_jpg(x):
    pattern = r"question_images/[^/]+\.jpg"
    return isinstance(x, str) and re.search(pattern, x)

for prefix, folders in groups.items():
    counter = Counter()

    for folder in folders:
        jsonl_file = os.path.join(folder, "vqa_filtered_qa_pairs.jsonl") #can be replaecd by the path of data generated by bench_sampling.py
        if not os.path.isfile(jsonl_file):
            continue

        with open(jsonl_file, "r", encoding="utf-8") as f:
            for line in f:
                item = json.loads(line)
                q = item.get("question", "")
                a = item.get("answer", "")
                s = item.get("solution", "")

                q_j = contains_jpg(q)
                a_j = contains_jpg(a)
                s_j = contains_jpg(s)

                if q_j and (not a_j) and (not s_j):
                    counter["q_only_img"] += 1

                elif (a_j or s_j) and (not q_j):
                    counter["as_only_img"] += 1

                elif q_j and (a_j or s_j):
                    counter["qas_all_img"] += 1

                else:
                    counter["no_img"] += 1

    total = sum(counter.values())
    ordered = OrderedDict()
    ordered["prefix"] = prefix

    for cls in ["q_only_img", "as_only_img", "qas_all_img", "no_img"]:
        cnt = counter.get(cls, 0)
        ratio = cnt / total if total > 0 else 0.0
        ordered[cls] = {
            "count": cnt,
            "ratio": round(ratio, 6)
        }

    final_stats[prefix] = ordered

for prefix, res in final_stats.items():
    print(f"【组：{prefix}】")
    for cls in ["q_only_img", "as_only_img", "qas_all_img", "no_img"]:
        c = res[cls]["count"]
        r = res[cls]["ratio"]
        print(f"  {cls:<14} count={c:<6} ratio={r:.4f}")
    print()